# Generated by Django 4.2 on 2023-04-18 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('index', models.DecimalField(decimal_places=0, max_digits=6)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(default=True, max_length=20)),
                ('link', models.CharField(default=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BestSellingProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('price', models.CharField(max_length=150, verbose_name='Цена')),
                ('past_price', models.CharField(max_length=150, verbose_name='Прошлая цена')),
                ('is_published', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='image/best_selling/')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('image', models.ImageField(null=True, upload_to='image/category/')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='TimeSell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название скидки')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TitleSliderCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название слайдера')),
            ],
            options={
                'verbose_name': 'Слайдер вначале',
                'verbose_name_plural': 'Слайдеры вначале',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='TitleSliderImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название картинки для слайдера')),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('available', models.BooleanField(default=True)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
                ('image', models.ImageField(null=True, upload_to='image/titleslider/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TitleSliderCategory', to='shop.titleslidercategory')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('slug', models.CharField(db_index=True, max_length=150, unique=True)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('last_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('uploaded', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(null=True, upload_to='image/product/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ('name',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
