# Generated by Django 4.2 on 2023-04-18 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_titlesliderimg_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='titlesliderimg',
            options={'ordering': ('title',), 'verbose_name': 'Настройка слайдера', 'verbose_name_plural': 'Настройка слайдера'},
        ),
    ]
