# Generated by Django 4.2 on 2023-04-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_category_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountsIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstorder', models.CharField(max_length=10)),
                ('appdiscounts', models.CharField(max_length=10)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
    ]
