# Generated by Django 4.2 on 2023-04-18 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_discountsindex'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountsindex',
            name='title',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
