# Generated by Django 4.2 on 2023-04-18 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_discountsindex_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImgloginUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название скидки')),
                ('image', models.ImageField(null=True, upload_to='image/imgloginuser/')),
            ],
        ),
    ]
