# Generated by Django 4.2 on 2023-04-19 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_imgloginuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImgloginUser',
        ),
    ]
