# Generated by Django 4.2 on 2023-04-20 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_delete_imgloginuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCompanyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название истории')),
                ('description', models.TextField(max_length=1000, verbose_name='Сама история')),
                ('imageall', models.ImageField(null=True, upload_to='image/about/imageall/')),
            ],
        ),
        migrations.AlterModelOptions(
            name='bestsellingproducts',
            options={'verbose_name': 'Лучшее предложение', 'verbose_name_plural': 'лучшие предложения'},
        ),
    ]
